### ISSUE TITLE
How to generate knn files?

### ISSUE THREAD

**Issue by songw-zju** [haibo-qiu/GFNet#1]
Hi, thanks for your great work and share the code!
When I try to reproduce your result, the error occurs because the knn fiiles don't exist. I would like to know how to generate knn files.

**Comment by haibo-qiu** [comment]
Hi there~

If there is no existing knn file, the code is supposed to generate a new one by itself, as you can see [this line](https://github.com/haibo-qiu/GFNet/blob/ffafd0a563254d2c436a0966b3ba42db92e011e1/libs/dataloader/SemanticKitti.py#L396)

I will double-check this issue for inference.
Thanks

**Comment by haibo-qiu** [comment]
I think this issue came from [line96-97](https://github.com/haibo-qiu/GFNet/blob/ffafd0a563254d2c436a0966b3ba42db92e011e1/libs/dataloader/SemanticKitti.py#L96) in `SemanticKITTI.py`, where I assert the same length of scan and KNN. Actually, the code can handle the non-knn existing situation.

Simple deleting these codes can fix the issue, and I will update the repo asap.

Thanks~

**Comment by songw-zju** [comment]
Thanks for your kind consideration! I have solved the problem.
