### ISSUE TITLE
About details.

### ISSUE THREAD

**Issue by huixiancheng** [haibo-qiu/GFNet#2]
Hi. Thanks for your open source work. I have some ques about details.
1. Look like you only use trans Data Aug in Train. And look like the data aug code is similar with salsanext. 
As far as I know, kprnet's special unfolding projection method, also called proj_version='v2' in your code, causes out-of-bounds errors when using data aug, which I think is the reason why you only use one type of aug. 
However, in my past experiments, errors occurred even when using only similar trans Data Aug.
So I want to know, did the data augmentation work fine in your experiment?
https://github.com/haibo-qiu/GFNet/blob/e2e8ededdde4dd0c98c720fd10115a9d93077695/configs/resnet_semantickitti.yaml#L65-L72
https://github.com/haibo-qiu/GFNet/blob/e2e8ededdde4dd0c98c720fd10115a9d93077695/libs/utils/laserscan.py#L103-L114

2. Have you studied the effect of different choices of K by KNN in kpconv? Your implementation chooses the same 7 as KPRNet, and I'm wondering if this affects performance.
https://github.com/haibo-qiu/GFNet/blob/ffafd0a563254d2c436a0966b3ba42db92e011e1/libs/dataloader/SemanticKitti.py#L395-L397

**Comment by haibo-qiu** [comment]
Hi there~
Thanks for your interest.

1. For the data aug problem, I tag these augs 'good' or 'bad' according to my visualizations of range images after applying corresponding data aug. As you said that aug like 'flip' and 'rot' will cause bound errors, but in my experiments 'trans' did generate meaningful range images, that's why I keep it. I guess the reason might be relatively small jitters (5, 3, 1 for x, y, z).

2. As for the choice of K in KNN, I just follow the setting of KPRNet and do not try other numbers.

**Comment by huixiancheng** [comment]
thx for  your reply.
