### ISSUE TITLE
images on dockerhub

### ISSUE THREAD

**Issue by wyw-dlut** [haibo-qiu/GFNet#3]
can u push it on dockerhub? QAQ

**Comment by haibo-qiu** [comment]
Hi @wyw-dlut 

I have no right to access the machines where I used docker for experiments anymore, so I can not directly push it to the docker hub now. 

The environment is based on `nvcr.io/nvidia/pytorch:20.12-py3` with several other packages, which can be trivially installed according to my own experiences.

**Comment by wyw-dlut** [comment]
i met the problem "AttributeError: 'NoneType' object has no attribute 'origin'", when i used the dokcerfile to build it. i used "nvcc _C" to check the version of the cuda, i found its 11.1, which does not fit the requirement mentioned in the environment.yml "pytorch=1.10.2=py3.7_cuda11.3_cudnn8.2.0_0".

**Comment by haibo-qiu** [comment]
> "AttributeError: 'NoneType' object has no attribute 'origin'"

It looks like this error is related to a certain package installation instead of the docker image build itself.

Thus I think you can build a container with the `nvcr.io/nvidia/pytorch:20.12-py3` image, and then manually install other packages (below) inside this container, which can help you locate where the error occurs. Then you can either use this container to generate a docker image or directly run experiments inside it. 

https://github.com/haibo-qiu/GFNet/blob/711f2695e1e9f34d63997be7ce0364f9c3c0ce0f/Dockerfile#L11-L16

By the way, the `Dockerfile` and `environment.yml`  are not corresponding to the same environment (`Dockerfile` pytorch1.8+cuda11.1, `environment.yml` pytorch1.10+cuda11.3). In my experiments, I have two machines with the above two environments for training and testing (but now I can not access the machine where I used docker). So the code are supposed to run successfully in both environments.

**Comment by wyw-dlut** [comment]
thx. i tried to install every packages into the container, it worked. thx again

**Comment by haibo-qiu** [comment]
No worries :)
